Fix PKCE problem
jamesholcombe/dash-auth-external pull request #11
Opened 2023-01-11 14:41 UTC by yoannspace

When not using PKCE, the program still falls back on PKCE boolean being true, which is wrong. So passing the existing variable to the rest of the functions.

2023-01-12 00:14 UTC, jamesholcombe requested changes
looks good, only comment is that default arguments to functions should not be mutable. None is preferred to dict. See https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/ for explanation

2023-01-12 08:09 UTC, yoannspace commented
Alright, I will leave out this Default to None. However, you should know that with None and kept as default the code fails at either:
- https://github.com/jamesholcombe/dash-auth-external/blob/1219c44f249802c153af9897378e53cd853e3c45/dash_auth_external/routes.py#L53 or
- https://github.com/jamesholcombe/dash-auth-external/blob/1219c44f249802c153af9897378e53cd853e3c45/dash_auth_external/routes.py#L58

Not being a Python developer, that was the fix for me, but I will then prefer setting the `auth_request_headers` myself in my code when calling the library. Thanks for the link, makes total sense.

2023-01-12 10:26 UTC, jamesholcombe commented
yes good spot thanks, I will fix this and add some tests and then merge this PR.

2023-01-15 13:22 UTC, jamesholcombe approved these changes

2023-01-15 13:23 UTC, merged